import React, {useState,useRef,useEffect,useCallback} from 'react';
import {Play,Pause,Plus,Minus,ArrowsOutCardinal,ArrowCounterClockwise,Eye,X,ArrowLeft,ArrowRight,BookOpen,ArrowUpRight,Check,MapTrifold} from '@phosphor-icons/react';
import {chapters,sources,formatAge} from './chapters';
const asset = n => `/assets/${n}.webp`;
function IconButton({label,children,...rest}){return <button className="icon-button" aria-label={label} title={label} {...rest}>{children}</button>}
function Modal({label,children,onClose,wide=false}){
 const ref=useRef();
 useEffect(()=>{const prev=document.activeElement;ref.current.showModal();return()=>prev?.focus()},[]);
 return <dialog ref={ref} className={wide?'modal wide':'modal'} onCancel={onClose} onClick={e=>{if(e.target===e.currentTarget)onClose()}} aria-label={label}><div className="modal-top"><span>{label}</span><IconButton label="Đóng" onClick={onClose}><X size={22}/></IconButton></div>{children}</dialog>
}
export function App(){
 const [index,setIndex]=useState(3),[age,setAge]=useState(508),[playing,setPlaying]=useState(false),[modal,setModal]=useState(null),[speed,setSpeed]=useState(1),[zoom,setZoom]=useState(1),[pan,setPan]=useState({x:0,y:0}),[dragging,setDragging]=useState(false),[imageReady,setImageReady]=useState(false);
 const scene=chapters[index],drag=useRef(null),stageRef=useRef(null),elapsed=useRef(0);
 const select=useCallback((i,stop=true)=>{setIndex(i);setAge(chapters[i].age);setZoom(1);setPan({x:0,y:0});setImageReady(false);elapsed.current=0;if(stop)setPlaying(false)},[]);
 useEffect(()=>{if(!playing)return;let previous=performance.now();const id=setInterval(()=>{const now=performance.now();elapsed.current+=(now-previous)*speed;previous=now;const duration=8500;if(elapsed.current>=duration){if(index===chapters.length-1){setPlaying(false);elapsed.current=0;return}select(index+1,false)}else{setAge(scene.start+(scene.end-scene.start)*(elapsed.current/duration))}},80);return()=>clearInterval(id)},[playing,index,speed,scene,select]);
 useEffect(()=>{chapters.forEach(c=>{const im=new Image();im.src=asset(c.image)})},[]);
 useEffect(()=>{const handler=e=>{if(modal||/INPUT|SELECT|BUTTON|TEXTAREA/.test(e.target.tagName))return;if(e.code==='Space'){e.preventDefault();setPlaying(v=>!v)}if(e.key==='ArrowRight')select(Math.min(index+1,chapters.length-1));if(e.key==='ArrowLeft')select(Math.max(index-1,0))};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler)},[index,modal,select]);
 const changeAge=value=>{setAge(value);setPlaying(false);elapsed.current=(scene.start-value)/(scene.start-scene.end)*8500};
 const play=()=>{if(index===chapters.length-1&&!playing)select(0,false);setPlaying(v=>!v)};
 const adjustZoom=delta=>setZoom(v=>Math.min(2.5,Math.max(1,Math.round((v+delta)*10)/10)));
 const reset=()=>{setZoom(1);setPan({x:0,y:0})};
 const localPercent=(scene.start-age)/(scene.start-scene.end)*100;
 const fullPercent=(4540-age)/4540*100;
 const portrait=scene.portrait||scene.image;
 const ticks=index===3?[539,530,520,510,500,490,485]:Array.from({length:6},(_,i)=>scene.start-(scene.start-scene.end)*i/5);
 const tickLabel=v=>index===3?Math.round(v):scene.start>=1000?(v/1000).toLocaleString('vi-VN',{maximumFractionDigits:2}):scene.start<3?(v*1000).toLocaleString('vi-VN',{maximumFractionDigits:v<.1?1:0}):Math.round(v);
 const unit=age>=1000?'tỷ năm trước':age<1?'nghìn năm trước':'triệu năm trước';
 return <div className="earth-app">
  <header className="site-header"><a className="brand" href="#" onClick={e=>{e.preventDefault();select(3)}} aria-label="Địa Cầu — về cảnh Cambri">ĐỊA CẦU</a><span className="brand-rule"/><span className="tagline">Bảo tàng sự sống</span><span className="header-rule"/><button className="journey-link" onClick={()=>{setModal('journey');setPlaying(false)}}>Hành trình Trái Đất <MapTrifold size={21} weight="light"/></button></header>
  <main className="experience">
   <section className="scene-column" aria-label="Cảnh hệ sinh thái">
    <div className={'scene-stage '+(dragging?'dragging':'')} ref={stageRef} onPointerDown={e=>{if(e.target.closest('button'))return;drag.current={x:e.clientX-pan.x,y:e.clientY-pan.y};e.currentTarget.setPointerCapture(e.pointerId);setDragging(true)}} onPointerMove={e=>{if(drag.current)setPan({x:Math.max(-180,Math.min(180,e.clientX-drag.current.x)),y:Math.max(-100,Math.min(100,e.clientY-drag.current.y))})}} onPointerUp={()=>{drag.current=null;setDragging(false)}} onPointerCancel={()=>{drag.current=null;setDragging(false)}}>
     <img key={scene.image} className='scene-image ready' src={asset(scene.image)} alt={`Phục dựng minh họa ${scene.name}: ${scene.environment}`} onLoad={()=>setImageReady(true)} draggable="false" style={{transform:`translate(${pan.x}px, ${pan.y}px) scale(${zoom})`}}/>
     <div className="scene-date"><span className="copper-rule"/><div className="era-name">{scene.name}</div><div className={'age-number '+(age===0?'present-age':'')}>{formatAge(age,false)}</div>{age!==0&&<div className="age-unit">{unit}</div>}</div>
     {index===3&&zoom===1&&pan.x===0&&<button className="hotspot" onClick={()=>{setModal('trilobite');setPlaying(false)}}><span className="hotspot-label">Bọ ba thùy</span><span className="hotspot-stem"/><span className="hotspot-point"/></button>}
    </div>
    <div className="scene-toolbar"><button className="play-button" onClick={play}>{playing?<Pause size={24} weight="fill"/>:<Play size={24} weight="fill"/>}<span>{playing?'Tạm dừng':'Phát hành trình'}</span></button><span className="drag-hint">Kéo để di chuyển cảnh</span><div className="scene-tools"><IconButton label="Đặt lại góc nhìn" onClick={reset}>{zoom!==1||pan.x!==0||pan.y!==0?<ArrowCounterClockwise size={22}/>:<ArrowsOutCardinal size={22}/>}</IconButton><IconButton label="Phóng to" disabled={zoom>=2.5} onClick={()=>adjustZoom(.2)}><Plus size={23}/></IconButton><IconButton label="Thu nhỏ" disabled={zoom<=1} onClick={()=>adjustZoom(-.2)}><Minus size={23}/></IconButton></div></div>
   </section>
   <aside className="journal" key={scene.id}><div className="eyebrow">ĐANG KHÁM PHÁ</div><h1 className={scene.title.length>32?"long-title":""}>{scene.title}</h1><p className="intro">{scene.description}</p><div className="journal-divider"/><button className="specimen-image-button" onClick={()=>{setModal('specimen');setPlaying(false)}} aria-label={`Quan sát ${scene.specimen}`}><img className="specimen-image" src={asset(portrait)} alt={scene.specimen}/></button><h2>{scene.specimen}</h2><p className="specimen-note">{scene.note}</p><button className="observe-button" onClick={()=>{setModal('specimen');setPlaying(false)}}><Eye size={22} weight="light"/>{index===0?'Khám phá môi trường':'Quan sát sinh vật'}</button><button className="source-link" onClick={()=>{setModal('sources');setPlaying(false)}}>Phục dựng minh họa <BookOpen size={13}/></button></aside>
  </main>
  <section className="time-panel" aria-label="Điều khiển dòng thời gian">
   <div className="local-heading"><h2>Phóng đại thời kỳ <span>·</span> <label className="sr-only" htmlFor="period">Chọn thời kỳ</label><select id="period" value={index} onChange={e=>select(Number(e.target.value))}>{chapters.map((c,i)=><option value={i} key={c.id}>{c.name}</option>)}</select></h2><span className="timeline-unit">{scene.start>=1000?'Tỷ năm trước':scene.start<3?'Nghìn năm trước':'Triệu năm trước'}</span></div>
   <div className="local-range-wrap"><input aria-label="Thời gian trong thời kỳ" className="timeline-range local-range" type="range" min="0" max="10000" step="1" value={Math.round(localPercent*100)} aria-valuetext={formatAge(age)} onChange={e=>changeAge(scene.start-(Number(e.target.value)/10000)*(scene.start-scene.end))}/><div className="tick-marks">{ticks.map((v,i)=><span key={i} className="tick" style={{left:`${(scene.start-v)/(scene.start-scene.end)*100}%`}}>{tickLabel(v)}</span>)}</div><div className="current-age" style={{left:`${Math.max(5,Math.min(95,localPercent))}%`}}>{formatAge(age,false)}<small>{age===0?'':unit}</small></div></div>
   <div className="overview-heading"><h3>Toàn bộ lịch sử Trái Đất</h3><div className="chapter-control"><IconButton label="Chặng trước" disabled={index===0} onClick={()=>select(index-1)}><ArrowLeft size={15}/></IconButton><span>{index+1} / {chapters.length} chặng</span><IconButton label="Chặng tiếp" disabled={index===chapters.length-1} onClick={()=>select(index+1)}><ArrowRight size={15}/></IconButton><button className="speed-button" aria-label={`Tốc độ phát ${speed} lần`} onClick={()=>setSpeed(v=>v===1?2:v===2?.5:1)}>{speed.toLocaleString('vi-VN')}×</button></div></div>
   <div className="overview-track"><input aria-label="Toàn bộ lịch sử Trái Đất" className="timeline-range full-range" type="range" min="0" max="4540" step=".01" value={4540-age} onKeyDown={e=>{if(['ArrowRight','ArrowLeft','Home','End'].includes(e.key)){e.preventDefault();select(e.key==='Home'?0:e.key==='End'?chapters.length-1:Math.max(0,Math.min(chapters.length-1,index+(e.key==='ArrowRight'?1:-1))))}}} aria-valuetext={`${scene.name}, ${formatAge(age)}`} onChange={e=>{const target=4540-Number(e.target.value);const nearest=chapters.reduce((best,c,i)=>Math.abs(c.age-target)<Math.abs(chapters[best].age-target)?i:best,0);select(nearest)}}/><div className="selection-window" style={{left:`${Math.min(97,Math.max(3,fullPercent))}%`}}/><div className="overview-labels"><span>4,54 tỷ năm trước</span><span>Hiện tại</span></div></div>
   <div className="timeline-footnote"><span>8 lát cắt tiêu biểu · Các mốc được làm tròn</span><button onClick={()=>{setModal('journey');setPlaying(false)}}>Khám phá các chặng <ArrowRight size={13}/></button></div>
  </section>
  {modal==='journey'&&<Modal label="Hành trình Trái Đất" onClose={()=>setModal(null)} wide><h2 className="modal-heading">4,54 tỷ năm. Một hành tinh sống.</h2><p className="modal-intro">Chọn một lát cắt để khám phá. Khi phát, hành trình đi lần lượt qua 8 cảnh tiêu biểu, không theo tốc độ thời gian tuyến tính.</p><div className="chapter-grid">{chapters.map((c,i)=><button key={c.id} className={'chapter-card '+(i===index?'selected':'')} onClick={()=>{select(i);setModal(null)}}><img src={asset(c.image)} alt=""/><div><span className="chapter-age">{formatAge(c.age)}</span><h3>{c.short}</h3><span className="chapter-era">{c.name}</span>{i===index&&<Check size={19}/>}</div></button>)}</div></Modal>}
  {(modal==='specimen'||modal==='trilobite')&&<Modal label={modal==='trilobite'?'Bọ ba thùy':scene.specimen} onClose={()=>setModal(null)} wide><div className="detail-layout"><img className="detail-image" src={asset(modal==='trilobite'?'cambrian':portrait)} alt={modal==='trilobite'?'Bọ ba thùy trong cảnh Cambri':scene.specimen}/><div><span className="eyebrow">{scene.name.toUpperCase()}</span><h2 className="modal-heading">{modal==='trilobite'?'Bọ ba thùy':scene.specimen}</h2><p>{modal==='trilobite'?'Bọ ba thùy là một nhóm chân khớp biển đã tuyệt chủng. Bộ xương ngoài phân đốt thường được bảo tồn thành hóa thạch. Hình ảnh trong cảnh là phục dựng minh họa, không đại diện cho mọi loài bọ ba thùy.':scene.detail}</p><dl><dt>Môi trường</dt><dd>{scene.environment}</dd><dt>Cảnh đại diện</dt><dd>{formatAge(scene.age)}</dd></dl><p className="detail-disclaimer">Ảnh phục dựng có thể phóng to trên cảnh chính. Đây chưa phải mô hình 3D có thể xoay.</p><button className="text-button" onClick={()=>setModal('sources')}>Đọc nguồn tham khảo <ArrowUpRight size={17}/></button></div></div></Modal>}
  {modal==='sources'&&<Modal label="Về bản phục dựng" onClose={()=>setModal(null)}><h2 className="modal-heading">Một cửa sổ nhìn về quá khứ</h2><p>Hình ảnh được tạo để minh họa không gian và sinh vật. Màu sắc, tỷ lệ và cách bố trí không phải dữ liệu đo đạc hay bản phục dựng cổ sinh vật học đã được thẩm định.</p><p>Bản tương tác này gồm 8 lát cắt chọn lọc. Kéo thanh tổng quan sẽ chọn chặng gần nhất; thanh phía trên điều chỉnh mốc trong giai đoạn đang xem. Trong mỗi chặng, hình ảnh đại diện giữ nguyên.</p><p>Ranh giới thời kỳ được làm tròn cho giao diện. Cảnh và nguồn gốc sự sống có những mức độ bất định khác nhau.</p><div className="source-list">{sources.map((s,i)=><a key={s.url} href={s.url} target="_blank" rel="noreferrer"><div><strong>{s.label}</strong><span>{s.name}</span></div><ArrowUpRight size={20}/></a>)}</div></Modal>}
 </div>
}
