export const chapters = [
 {id:'hadean',name:'Liên đại Hỏa Thành',short:'Trái Đất sơ khai',age:4500,start:4540,end:4000,title:'Khởi đầu từ lửa',description:'Một hành tinh non trẻ đang hình thành. Va chạm, đá nóng chảy và núi lửa định hình bề mặt Trái Đất.',specimen:'Một thế giới chưa có sự sống',note:'Chưa có bằng chứng xác nhận sự sống ở giai đoạn minh họa này.',detail:'Trái Đất hình thành cách đây khoảng 4,54 tỷ năm. Cảnh núi lửa là minh họa cho một phần môi trường sơ khai, không phải bản đồ địa hình hay nhiệt độ toàn cầu.',environment:'Đá nóng chảy · núi lửa',life:'Chưa có bằng chứng xác nhận',image:'hadean',sources:[1]},
 {id:'archean',name:'Liên đại Thái Cổ',short:'Dấu vết sự sống',age:3500,start:4000,end:2500,title:'Sự sống từ những điều nhỏ bé',description:'Trong những vùng nước nông, các cộng đồng vi sinh vật để lại dấu vết trên đá. Một hành tinh sống bắt đầu mở ra.',specimen:'Stromatolite',note:'Cấu trúc phân lớp hình thành nhờ hoạt động của các cộng đồng vi sinh vật.',detail:'Stromatolite là một dạng bằng chứng quan trọng về sự sống cổ. Mốc trong hành trình là đại diện, không phải ngày xuất hiện chính xác của sự sống đầu tiên.',environment:'Biển nông · bờ đá',life:'Các cộng đồng vi sinh vật',image:'archean',sources:[1,2]},
 {id:'snowball',name:'Kỷ Cryogen',short:'Trái Đất băng giá',age:650,start:720,end:635,title:'Hành tinh trong băng',description:'Những đợt băng hà lớn biến đổi môi trường sống. Sự sống vi sinh vẫn tồn tại trong các môi trường thích hợp.',specimen:'Sự sống dưới băng',note:'Một cảnh đại diện cho giai đoạn băng hà, không phải toàn bộ lịch sử Tiền Cambri.',detail:'Mức độ phủ băng và các nơi trú ẩn của sự sống vẫn được nghiên cứu. Bản phục dựng thể hiện giả thuyết về một thế giới băng giá; không dùng để suy ra địa hình cụ thể.',environment:'Băng hà · biển lạnh',life:'Sự sống vi sinh',image:'snowball',sources:[0]},
 {id:'cambrian',name:'Kỷ Cambri',short:'Thế giới dưới biển',age:508,start:539,end:485,title:'Một thế giới dưới biển',description:'Khám phá môi trường biển cổ đại và những dạng sống tiêu biểu của kỷ Cambri.',specimen:'Anomalocaris',note:'Sinh vật săn mồi với các thùy bơi và đôi phần phụ phía trước.',detail:'Anomalocaris là một động vật thuộc nhóm Radiodonta. Cùng với bọ ba thùy và nhiều động vật biển khác, nó gợi lại sự đa dạng của các hệ sinh thái Cambri. Màu sắc và mô mềm trong hình là phục dựng minh họa.',environment:'Biển nông · đáy trầm tích',life:'Bọ ba thùy · Radiodonta · bọt biển',image:'cambrian',portrait:'anomalocaris',sources:[3]},
 {id:'carboniferous',name:'Kỷ Carbon',short:'Rừng đầm lầy',age:320,start:359,end:299,title:'Khi những khu rừng vươn cao',description:'Rừng đầm lầy với thực vật cổ tạo nên những cảnh quan xanh dày đặc ở một số vùng nhiệt đới.',specimen:'Rừng thực vật cổ',note:'Thạch tùng thân gỗ, mộc tặc và các nhóm dương xỉ tạo nên thảm thực vật đa tầng.',detail:'Nhiều trầm tích giàu vật chất thực vật của kỷ Carbon về sau trở thành than đá. Cảnh là một hệ sinh thái tiêu biểu; không phải mọi vùng trên Trái Đất đều là rừng đầm lầy.',environment:'Đầm lầy · khí hậu ẩm',life:'Thực vật có mạch · chân khớp',image:'carboniferous',sources:[0,1]},
 {id:'jurassic',name:'Kỷ Jura',short:'Thời đại khủng long',age:150,start:201,end:145,title:'Dưới bóng những loài khổng lồ',description:'Giữa các khu rừng lá kim và dương xỉ, những nhóm khủng long đa dạng chia sẻ một thế giới giàu sự sống.',specimen:'Khủng long cổ dài',note:'Các loài sauropod là một trong những nhóm động vật ăn thực vật tiêu biểu.',detail:'Cảnh chọn một hệ sinh thái cuối kỷ Jura. Khủng long không sống trong một thời điểm duy nhất: nhiều loài nổi tiếng cách nhau hàng chục triệu năm và không cùng tồn tại.',environment:'Rừng lá kim · đồng bằng',life:'Sauropod · Stegosaurus · dương xỉ',image:'jurassic',sources:[1,4]},
 {id:'iceage',name:'Thế Pleistocen',short:'Kỷ băng hà gần đây',age:0.02,start:2.58,end:0.0117,title:'Những bước chân trên thảo nguyên lạnh',description:'Trong các giai đoạn lạnh, băng hà và thảo nguyên lạnh mở rộng ở nhiều vùng. Những loài thú lớn thích nghi với môi trường khắc nghiệt.',specimen:'Voi ma mút lông dài',note:'Lông dày và những đặc điểm cơ thể giúp chúng sống trong môi trường lạnh.',detail:'Mốc 20 nghìn năm trước gần giai đoạn cực đại băng hà cuối cùng. Trái Đất không hoàn toàn đóng băng; vẫn có nhiều hệ sinh thái khác nhau theo vĩ độ và địa hình.',environment:'Thảo nguyên lạnh · băng hà',life:'Voi ma mút · động vật có vú',image:'iceage',sources:[0]},
 {id:'present',name:'Hiện tại',short:'Hành tinh của chúng ta',age:0,start:0.0117,end:0,title:'Sự sống vẫn đang viết tiếp',description:'Rừng, sông và vô số hệ sinh thái cùng tồn tại trên hành tinh hiện đại. Con người là một phần của câu chuyện ấy.',specimen:'Đa dạng sinh học',note:'Mỗi hệ sinh thái là một mạng lưới liên hệ giữa sinh vật và môi trường.',detail:'Một cảnh rừng hiện đại là đại diện cho một trong nhiều môi trường của Trái Đất. Hành trình này giới thiệu các lát cắt chọn lọc, không mô phỏng đầy đủ mọi thời kỳ, khu vực hay quá trình tiến hóa.',environment:'Rừng hiện đại · sông',life:'Thực vật · động vật · con người',image:'present',sources:[1]}
];
export const sources = [
 {name:'International Commission on Stratigraphy',label:'Thang thời gian địa chất',url:'https://stratigraphy.org/chart/'},
 {name:'Natural History Museum',label:'Nguồn gốc và lịch sử sự sống',url:'https://www.nhm.ac.uk/discover/origin-of-life-on-earth.html'},
 {name:'Natural History Museum',label:'Stromatolite và sự sống cổ',url:'https://www.nhm.ac.uk/discover/news/2022/november/oldest-evidence-life-earth-could-help-discover-ancient-life-mars.html'},
 {name:'Natural History Museum',label:'Hệ sinh thái kỷ Cambri',url:'https://www.nhm.ac.uk/discover/the-cambrian-period.html'},
 {name:'Natural History Museum',label:'Các chặng đường tiến hóa',url:'https://www.nhm.ac.uk/discover/timeline-wall.html'}
];
export function formatAge(age,unit=true){if(age===0)return 'Hiện tại'; if(age>=1000)return `${(age/1000).toLocaleString('vi-VN',{maximumFractionDigits:2})}${unit?' tỷ năm trước':''}`; if(age<1)return `${(age*1000).toLocaleString('vi-VN',{maximumFractionDigits:1})}${unit?' nghìn năm trước':''}`;return `${age.toLocaleString('vi-VN',{maximumFractionDigits:1})}${unit?' triệu năm trước':''}`;}
